import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'si' | 'en' | 'ta';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  si: {
    // Header
    'header.brand': 'AgriConnect',
    'header.subtitle': 'ගැනුම්කරු උපකරණ පුවරුව',
    'header.search': 'බීජ, පොහොර, උපකරණ සොයන්න...',
    'header.delivery': 'බෙදාහැරීම',
    'header.alerts': 'ප්‍රතිවේදන',
    'header.profile': 'පැතිකඩ',

    // Navigation
    'nav.title': 'සම්පත් සොයන්න',
    'nav.subtitle': 'සාර්ථක ගොවිතැන සඳහා අවශ්‍ය සියල්ල සොයන්න',
    'nav.seeds': 'බීජ',
    'nav.fertilizers': 'පොහොර',
    'nav.equipment': 'උපකරණ',
    'nav.vehicles': 'වාහන',
    'nav.advisory': 'උපදේශන',
    'nav.reviews': 'සමාලෝචන',
    'nav.seeds.desc': 'සියළුම භෝග සඳහා ගුණාත්මක බීජ',
    'nav.fertilizers.desc': 'කාබනික සහ රසායනික පොහොර',
    'nav.equipment.desc': 'ගොවිතැන් මෙවලම් සහ යන්ත්‍රෝපකරණ',
    'nav.vehicles.desc': 'ට්‍රැක්ටර් සහ ප්‍රවාහන වාහන',
    'nav.advisory.desc': 'ගවේෂණ ගොවිතැන් උපදේශන',
    'nav.reviews.desc': 'නිෂ්පාදන ශ්‍රේණිගත කිරීම් සහ ප්‍රතිපෝෂණ',
    'nav.items': 'අයිතම',

    // Profile Page
    'profile.title': 'මගේ පැතිකඩ',
    'profile.subtitle': 'ඔබගේ පැතිකඩ සහ නිෂ්පාදන/සේවා කළමනාකරණය කරන්න',
    'profile.backToDashboard': 'උපකරණ පුවරුවට යන්න',
    'profile.selectRole': 'ඔබගේ භූමිකාව තෝරන්න',
    'profile.supplier': 'සැපයුම්කරු',
    'profile.advisor': 'උපදේශක',
    'profile.supplierDesc': 'කෘෂිකාර්මික නිෂ්පාදන සහ සේවා සපයන්න',
    'profile.advisorDesc': 'ගොවිතැන් උපදේශන සහ ගවේෂණ ඥානය බෙදාගන්න',
    'profile.businessInfo': 'ව්‍යාපාරික තොරතුරු',
    'profile.businessName': 'ව්‍යාපාර නම',
    'profile.contactPerson': 'සම්බන්ධතා පුද්ගලයා',
    'profile.email': 'විද්‍යුත් ලිපිනය',
    'profile.phone': 'දුරකථන අංකය',
    'profile.address': 'ලිපිනය',
    'profile.district': 'දිස්ත්‍රික්කය',
    'profile.province': 'පළාත',
    'profile.description': 'විස්තරය',
    'profile.website': 'වෙබ් අඩවිය',
    'profile.established': 'ස්ථාපිත වර්ෂය',
    'profile.specialization': 'විශේෂඥතා',
    'profile.certification': 'සහතික',
    'profile.experience': 'අත්දැකීම්',
    'profile.save': 'සුරකින්න',
    'profile.cancel': 'අවලංගු කරන්න',
    'profile.edit': 'සංස්කරණය කරන්න',
    'profile.myProducts': 'මගේ නිෂ්පාදන',
    'profile.myServices': 'මගේ සේවා',
    'profile.addProduct': 'නිෂ්පාදනය එක් කරන්න',
    'profile.addService': 'සේවාව එක් කරන්න',
    'profile.manageInventory': 'තොග කළමනාකරණය',
    'profile.productName': 'නිෂ්පාදන නම',
    'profile.serviceName': 'සේවා නම',
    'profile.category': 'ප්‍රභේදය',
    'profile.price': 'මිල',
    'profile.quantity': 'ප්‍රමාණය',
    'profile.unit': 'ඒකකය',
    'profile.quality': 'ගුණාත්මකභාවය',
    'profile.images': 'පින්තූර',
    'profile.uploadImages': 'පින්තූර උඩුගත කරන්න',
    'profile.availability': 'පවතින බව',
    'profile.inStock': 'තොගයේ ඇත',
    'profile.outOfStock': 'තොගයෙන් අවසන්',
    'profile.lowStock': 'අඩු තොගයක්',
    'profile.qualityGrade': 'ගුණාත්මක ශ්‍රේණිය',
    'profile.organic': 'කාබනික',
    'profile.conventional': 'සම්ප්‍රදායික',
    'profile.premium': 'ප්‍රිමියම්',
    'profile.standard': 'සම්මත',
    'profile.harvestDate': 'අස්වනු දිනය',
    'profile.expiryDate': 'කල් ඉකුත් වන දිනය',
    'profile.storageConditions': 'ගබඩා තත්ත්වයන්',
    'profile.minimumOrder': 'අවම ඇණවුම',
    'profile.deliveryOptions': 'බෙදාහැරීම් විකල්ප',
    'profile.freeDelivery': 'නොමිලේ බෙදාහැරීම',
    'profile.paidDelivery': 'ගෙවන බෙදාහැරීම',
    'profile.selfPickup': 'ස්වයං ගැනීම',
    'profile.statistics': 'සංඛ්‍යාලේඛන',
    'profile.totalProducts': 'මුළු නිෂ්පාදන',
    'profile.totalServices': 'මුළු සේවා',
    'profile.totalOrders': 'මුළු ඇණවුම්',
    'profile.rating': 'ශ්‍රේණිගත කිරීම',
    'profile.reviews': 'සමාලෝචන',
    'profile.recentActivity': 'මෑත ක්‍රියාකාරකම්',
    'profile.orderHistory': 'ඇණවුම් ඉතිහාසය',

    // Enhanced Product Fields
    'profile.productListings': 'නිෂ්පාදන ලැයිස්තුව',
    'profile.nutritionalLevel': 'පෝෂණ මට්ටම',
    'profile.ingredients': 'සංඝටක',
    'profile.addIngredient': 'සංඝටකය එක් කරන්න',
    'profile.ingredientName': 'සංඝටකයේ නම',
    'profile.percentage': 'ප්‍රතිශතය',
    'profile.npkRatio': 'NPK අනුපාතය',
    'profile.nitrogen': 'නයිට්‍රජන් (N)',
    'profile.phosphorus': 'පොස්පරස් (P)',
    'profile.potassium': 'පොටෑසියම් (K)',
    'profile.organicMatter': 'කාබනික ද්‍රව්‍ය',
    'profile.moisture': 'ජල අන්තර්ගතය',
    'profile.ph': 'pH මට්ටම',
    'profile.micronutrients': 'ක්ෂුද්‍ර පෝෂ්‍ය ද්‍රව්‍ය',
    'profile.applicationRate': 'යෙදවීමේ අනුපාතය',
    'profile.applicationMethod': 'යෙදවීමේ ක්‍රමය',
    'profile.soilType': 'පස් වර්ගය',
    'profile.cropSuitability': 'භෝග සුදුසුභාවය',
    'profile.packagingInfo': 'ඇසුරුම් තොරතුරු',
    'profile.packagingSize': 'ඇසුරුම් ප්‍රමාණය',
    'profile.brandName': 'වෙළඳ නාමය',
    'profile.manufacturerInfo': 'නිෂ්පාදකයා',
    'profile.batchNumber': 'කණ්ඩායම් අංකය',
    'profile.manufactureDate': 'නිෂ්පාදන දිනය',
    'profile.registrationNumber': 'ලියාපදිංචි අංකය',
    'profile.safetyInstructions': 'ආරක්ෂණ උපදේශන',
    'profile.productImages': 'නිෂ්පාදන පින්තූර',
    'profile.primaryImage': 'ප්‍රධාන පින්තූර',
    'profile.additionalImages': 'අමතර පින්තූර',
    'profile.productCertificates': 'නිෂ්පාදන සහතික',
    'profile.qualityCertificate': 'ගුණාත්මක සහතිකය',
    'profile.organicCertificate': 'කාබනික සහතිකය',
    'profile.testReports': 'පරීක්ෂණ වාර්තා',

    // Delivery Page
    'delivery.title': 'බෙදාහැරීම් ලුහුබඳින්න',
    'delivery.subtitle': 'ඔබගේ ඇණවුම් සහ බෙදාහැරීම් ලුහුබඳින්න',
    'delivery.backToDashboard': 'උපකරණ පුවරුවට යන්න',
    'delivery.activeDeliveries': 'සක්‍රීය බෙදාහැරීම්',
    'delivery.manualTrack': 'අත්‍යවශ්‍ය ලුහුබඳිනවා',
    'delivery.trackingNumber': 'ලුහුබඳින අංකය',
    'delivery.enterTracking': 'ලුහුබඳින අංකය ඇතුළත් කරන්න',
    'delivery.trackButton': 'ලුහුබඳින්න',
    'delivery.recentDeliveries': 'මෑත බෙදාහැරීම්',
    'delivery.allDeliveries': 'සියලු බෙදාහැරීම්',
    'delivery.orderNumber': 'ඇණවුම් අංකය',
    'delivery.status': 'තත්ත්වය',
    'delivery.estimatedDelivery': 'ඇස්තමේන්තුගත බෙදාහැරීම',
    'delivery.location': 'ස්ථානය',
    'delivery.viewDetails': 'විස්තර බලන්න',
    'delivery.contactDriver': 'රියදුරු අමතන්න',
    'delivery.orderPlaced': 'ඇණවුම ලබා දීම',
    'delivery.processing': 'සැකසීම',
    'delivery.shipped': 'නැව්ගත කිරීම',
    'delivery.outForDelivery': 'බෙදාහැරීම සඳහා පිට වුණා',
    'delivery.delivered': 'බෙදාහැර ඇත',
    'delivery.cancelled': 'අවලංගු කරන ලදී',
    'delivery.trackingId': 'ලුහුබඳින හැඳුනුම්පත',
    'delivery.estimatedTime': 'ඇස්තමේන්තුගත කාලය',
    'delivery.currentLocation': 'වර්තමාන ස්ථානය',
    'delivery.nextUpdate': 'ඊළඟ යාවත්කාලීනය',
    'delivery.driverInfo': 'රියදුරු තොරතුරු',
    'delivery.vehicleInfo': 'වාහන තොරතුරු',
    'profile.specialInstructions': 'විශේෂ උපදේශන',

    // Filters
    'filters.title': 'පෙරහන්',
    'filters.advanced': 'උසස්',
    'filters.location': 'ස්ථානය',
    'filters.price': 'මිල පරාසය (₹)',
    'filters.min': 'අවම',
    'filters.max': 'උපරිම',
    'filters.showing': 'ප්‍රතිඵල පෙන්වයි',
    'filters.clear': 'සියල්ල ඉවත් කරන්න',
    'filters.apply': 'පෙරහන් යොදන්න',
    'filters.nearMe': 'මා ළඟ (කි.මී. 50)',
    'filters.withinState': 'ප්‍රාන්තය තුළ',
    'filters.nationwide': 'රටපුරා',

    // Seeds filters
    'filters.seeds.cropType': 'භෝග වර්ගය',
    'filters.seeds.variety': 'ප්‍රභේදය',
    'filters.seeds.season': 'වාරය',
    'filters.seeds.wheat': 'තිරිඟු',
    'filters.seeds.rice': 'සහල්',
    'filters.seeds.corn': 'ඉරිඟු',
    'filters.seeds.vegetables': 'එළවළු',
    'filters.seeds.fruits': 'පලතුරු',
    'filters.seeds.hybrid': 'දෙමුහුන්',
    'filters.seeds.organic': 'කාබනික',
    'filters.seeds.traditional': 'සම්ප්‍රදායික',
    'filters.seeds.gmo': 'GMO',
    'filters.seeds.kharif': 'කරීෆ්',
    'filters.seeds.rabi': 'රබී',
    'filters.seeds.zaid': 'සයිද්',

    // Fertilizers filters
    'filters.fertilizers.type': 'වර්ගය',
    'filters.fertilizers.npk': 'NPK අනුපාතය',
    'filters.fertilizers.application': 'යෙදවීම',
    'filters.fertilizers.organic': 'කාබනික',
    'filters.fertilizers.chemical': 'රසායනික',
    'filters.fertilizers.bio': 'ජෛව-පොහොර',
    'filters.fertilizers.liquid': 'ද්‍රව',
    'filters.fertilizers.soil': 'පස',
    'filters.fertilizers.foliar': 'කොළ',
    'filters.fertilizers.drip': 'බිංදු',
    'filters.fertilizers.broadcast': 'විකිර්ණය',

    // Products
    'products.found': 'නිෂ්පාදන හමු විය',
    'products.showing': 'ප්‍රතිඵල පෙන්වයි',
    'products.sortBy': 'අනුක්‍රමිකව:',
    'products.relevance': 'අදාළත්වය',
    'products.priceLow': 'මිල: අඩුවේ සිට ඉහළ',
    'products.priceHigh': 'මිල: ඉහළ සිට අඩුවේ',
    'products.rating': 'පාරිභෝගික ශ්‍රේණිගත කිරීම',
    'products.newest': 'අලුත්ම පළමුව',
    'products.addToCart': 'කරත්තයට එක් කරන්න',
    'products.by': 'විසින්',
    'products.inStock': 'තොගයේ ඇත',
    'products.outOfStock': 'තොගයෙන් අවසන්',
    'products.freeDelivery': 'නොමිලේ බෙදා හැරීම',
    'products.loadMore': 'තවත් නිෂ්පාදන පූරණය කරන්න',
    'products.noFound': 'නිෂ්පාදන හමු නොවීය',
    'products.noFoundDesc': 'ඔබගේ පෙරහන් හෝ සෙවීම් පද සකසා බලන්න',

    // Footer
    'footer.description': 'ගුණාත්මක කෘෂිකාර්මික සම්පත් සහ ගවේෂණ උපදේශන සමඟ ගොවීන් සම්බන්ධ කිරීම.',
    'footer.quickLinks': 'ඉක්මන් සම්බන්ධතා',
    'footer.aboutUs': 'අප ගැන',
    'footer.contact': 'අමතන්න',
    'footer.support': 'සහාය',
    'footer.faq': 'නිතර අසන ප්‍රශ්න',
    'footer.categories': 'ප්‍රභේද',
    'footer.contactInfo': 'සම්බන්ධතා තොරතුරු',
    'footer.rights': '© 2025 AgriConnect. සියලුම හිමිකම් ඇවිරිණි.',

    // Language Switcher
    'lang.sinhala': 'සිංහල',
    'lang.english': 'English',
    'lang.tamil': 'தமிழ்',
    'lang.selectLanguage': 'භාෂාව තෝරන්න',

    // Sample Products (Sinhala)
    'product.wheat.name': 'වගා තිරිඟු බීජ - HD-2967',
    'product.wheat.desc': 'ජලනල කරන ලද තත්ත්වයන් සඳහා සුදුසු ඉහළ අස්වැන්න ලබා දෙන තිරිඟු ප්‍රභේදය. රෝග ප්‍රතිරෝධී ඉතා ගුණාත්මක ධාන්‍ය ගුණය.',
    'product.fertilizer.name': 'කාබනික NPK පොහොර 10-26-26',
    'product.fertilizer.desc': 'සියලුම භෝග සඳහා සම්පූර්ණ පෝෂණය. මූල වර්ධනය වැඩි දියුණු කර පාංශු සෞඛ්‍යය වැඩි දියුණු කරයි.',
    'product.thresher.name': 'බහු-භෝග කුඩු යන්ත්‍රය',
    'product.thresher.desc': 'තිරිඟු, සහල් සහ කඩල සඳහා කාර්යක්ෂම කුඩු යන්ත්‍රය. ශ්‍රම පිරිවැය 70% කින් අඩු කරයි.',
    'product.tractor.name': 'මහින්ද්‍රා 475 DI ට්‍රැක්ටරය',
    'product.tractor.desc': 'ඉතා ඉන්ධන කාර්යක්ෂමතාව සහිත HP 47 ට්‍රැක්ටරය. මධ්‍යම සිට විශාල ගොවිපල සඳහා පරිපූර්ණ.',
    'product.tomato.name': 'දෙමුහුන් තක්කාලි බීජ - ආර්ක රක්ෂක්',
    'product.tomato.desc': 'ඉහළ අස්වැන්න ලබා ගැනීමේ හැකියාව සහිත රෝග ප්‍රතිරෝධී දෙමුහුන් තක්කාලි ප්‍රභේදය. හරිතාගාර වගාව සඳහා සුදුසු.',
    'product.compost.name': 'ජෛව-කාබනික කොම්පෝස්ට් පොහොර',
    'product.compost.desc': 'ගව ගොම සහ කුස්සියෙන් සාදන ලද 100% කාබනික කොම්පෝස්ට්. පස් ව්‍යුහය වැඩිදියුණු කරයි.',
  },
  en: {
    // Header
    'header.brand': 'AgriConnect',
    'header.subtitle': 'Buyer Dashboard',
    'header.search': 'Search seeds, fertilizers, equipment...',
    'header.delivery': 'Delivery',
    'header.alerts': 'Alerts',
    'header.profile': 'Profile',

    // Navigation
    'nav.title': 'Browse Resources',
    'nav.subtitle': 'Find everything you need for successful farming',
    'nav.seeds': 'Seeds',
    'nav.fertilizers': 'Fertilizers',
    'nav.equipment': 'Equipment',
    'nav.vehicles': 'Vehicles',
    'nav.advisory': 'Advisory',
    'nav.reviews': 'Reviews',
    'nav.seeds.desc': 'Quality seeds for all crops',
    'nav.fertilizers.desc': 'Organic & chemical fertilizers',
    'nav.equipment.desc': 'Farming tools & machinery',
    'nav.vehicles.desc': 'Tractors & transport vehicles',
    'nav.advisory.desc': 'Expert farming advice',
    'nav.reviews.desc': 'Product ratings & feedback',
    'nav.items': 'items',

    // Profile Page
    'profile.title': 'My Profile',
    'profile.subtitle': 'Manage your profile and products/services',
    'profile.backToDashboard': 'Back to Dashboard',
    'profile.selectRole': 'Select Your Role',
    'profile.supplier': 'Supplier',
    'profile.advisor': 'Advisor',
    'profile.supplierDesc': 'Supply agricultural products and services',
    'profile.advisorDesc': 'Share farming expertise and guidance',
    'profile.businessInfo': 'Business Information',
    'profile.businessName': 'Business Name',
    'profile.contactPerson': 'Contact Person',
    'profile.email': 'Email Address',
    'profile.phone': 'Phone Number',
    'profile.address': 'Address',
    'profile.district': 'District',
    'profile.province': 'Province',
    'profile.description': 'Description',
    'profile.website': 'Website',
    'profile.established': 'Year Established',
    'profile.specialization': 'Specialization',
    'profile.certification': 'Certifications',
    'profile.experience': 'Experience',
    'profile.save': 'Save',
    'profile.cancel': 'Cancel',
    'profile.edit': 'Edit',
    'profile.myProducts': 'My Products',
    'profile.myServices': 'My Services',
    'profile.addProduct': 'Add Product',
    'profile.addService': 'Add Service',
    'profile.manageInventory': 'Manage Inventory',
    'profile.productName': 'Product Name',
    'profile.serviceName': 'Service Name',
    'profile.category': 'Category',
    'profile.price': 'Price',
    'profile.quantity': 'Quantity',
    'profile.unit': 'Unit',
    'profile.quality': 'Quality',
    'profile.images': 'Images',
    'profile.uploadImages': 'Upload Images',
    'profile.availability': 'Availability',
    'profile.inStock': 'In Stock',
    'profile.outOfStock': 'Out of Stock',
    'profile.lowStock': 'Low Stock',
    'profile.qualityGrade': 'Quality Grade',
    'profile.organic': 'Organic',
    'profile.conventional': 'Conventional',
    'profile.premium': 'Premium',
    'profile.standard': 'Standard',
    'profile.harvestDate': 'Harvest Date',
    'profile.expiryDate': 'Expiry Date',
    'profile.storageConditions': 'Storage Conditions',
    'profile.minimumOrder': 'Minimum Order',
    'profile.deliveryOptions': 'Delivery Options',
    'profile.freeDelivery': 'Free Delivery',
    'profile.paidDelivery': 'Paid Delivery',
    'profile.selfPickup': 'Self Pickup',
    'profile.statistics': 'Statistics',
    'profile.totalProducts': 'Total Products',
    'profile.totalServices': 'Total Services',
    'profile.totalOrders': 'Total Orders',
    'profile.rating': 'Rating',
    'profile.reviews': 'Reviews',
    'profile.recentActivity': 'Recent Activity',
    'profile.orderHistory': 'Order History',

    // Enhanced Product Fields
    'profile.productListings': 'Product Listings',
    'profile.nutritionalLevel': 'Nutritional Level',
    'profile.ingredients': 'Ingredients',
    'profile.addIngredient': 'Add Ingredient',
    'profile.ingredientName': 'Ingredient Name',
    'profile.percentage': 'Percentage',
    'profile.npkRatio': 'NPK Ratio',
    'profile.nitrogen': 'Nitrogen (N)',
    'profile.phosphorus': 'Phosphorus (P)',
    'profile.potassium': 'Potassium (K)',
    'profile.organicMatter': 'Organic Matter',
    'profile.moisture': 'Moisture Content',
    'profile.ph': 'pH Level',
    'profile.micronutrients': 'Micronutrients',
    'profile.applicationRate': 'Application Rate',
    'profile.applicationMethod': 'Application Method',
    'profile.soilType': 'Soil Type',
    'profile.cropSuitability': 'Crop Suitability',
    'profile.packagingInfo': 'Packaging Information',
    'profile.packagingSize': 'Packaging Size',
    'profile.brandName': 'Brand Name',
    'profile.manufacturerInfo': 'Manufacturer Information',
    'profile.batchNumber': 'Batch Number',
    'profile.manufactureDate': 'Manufacture Date',
    'profile.registrationNumber': 'Registration Number',
    'profile.safetyInstructions': 'Safety Instructions',
    'profile.productImages': 'Product Images',
    'profile.primaryImage': 'Primary Image',
    'profile.additionalImages': 'Additional Images',
    'profile.productCertificates': 'Product Certificates',
    'profile.qualityCertificate': 'Quality Certificate',
    'profile.organicCertificate': 'Organic Certificate',
    'profile.testReports': 'Test Reports',

    // Delivery Page
    'delivery.title': 'Track Deliveries',
    'delivery.subtitle': 'Monitor your orders and deliveries',
    'delivery.backToDashboard': 'Back to Dashboard',
    'delivery.activeDeliveries': 'Active Deliveries',
    'delivery.manualTrack': 'Manual Tracking',
    'delivery.trackingNumber': 'Tracking Number',
    'delivery.enterTracking': 'Enter tracking number',
    'delivery.trackButton': 'Track',
    'delivery.recentDeliveries': 'Recent Deliveries',
    'delivery.allDeliveries': 'All Deliveries',
    'delivery.orderNumber': 'Order Number',
    'delivery.status': 'Status',
    'delivery.estimatedDelivery': 'Estimated Delivery',
    'delivery.location': 'Location',
    'delivery.viewDetails': 'View Details',
    'delivery.contactDriver': 'Contact Driver',
    'delivery.orderPlaced': 'Order Placed',
    'delivery.processing': 'Processing',
    'delivery.shipped': 'Shipped',
    'delivery.outForDelivery': 'Out for Delivery',
    'delivery.delivered': 'Delivered',
    'delivery.cancelled': 'Cancelled',
    'delivery.trackingId': 'Tracking ID',
    'delivery.estimatedTime': 'Estimated Time',
    'delivery.currentLocation': 'Current Location',
    'delivery.nextUpdate': 'Next Update',
    'delivery.driverInfo': 'Driver Information',
    'delivery.vehicleInfo': 'Vehicle Information',
    'delivery.specialInstructions': 'Special Instructions',

    // Add more English translations...
    'filters.title': 'Filters',
    'products.found': 'Products Found',
    'footer.description': 'Connecting farmers with quality agricultural resources and expert advice.',
    'lang.sinhala': 'සිංහල',
    'lang.english': 'English',
    'lang.tamil': 'தமிழ்',
    'lang.selectLanguage': 'Select Language',
  },
  ta: {
    // Header
    'header.brand': 'AgriConnect',
    'header.subtitle': 'வாங்குனர் கட்டுப்பாட்டு பலகம்',
    'header.search': 'விதைகள், உரங்கள், கருவிகளை தேடவும்...',
    'header.delivery': 'விநியோகம்',
    'header.alerts': 'அறிவிப்புகள்',
    'header.profile': 'சுயவிவரம்',

    // Navigation
    'nav.title': 'வளங்களை உலாவவும்',
    'nav.subtitle': 'வெற்றிகரமான விவசாயத்திற்கு தேவையான அனைத்தையும் கண்டறியவும்',
    'nav.seeds': 'விதைகள்',
    'nav.fertilizers': 'உரங்கள்',
    'nav.equipment': 'கருவிகள்',
    'nav.vehicles': 'வாகனங்கள்',
    'nav.advisory': 'ஆலோசனை',
    'nav.reviews': 'மதிப்புரைகள்',

    // Profile Page
    'profile.title': 'என் சுயவிவரம்',
    'profile.subtitle': 'உங்கள் சுயவிவரம் மற்றும் தயாரிப்புகள்/சேவைகளை நிர்வகிக்கவும்',
    'profile.backToDashboard': 'டாஷ்போர்டுக்கு திரும்பு',
    'profile.selectRole': 'உங்கள் பாத்திரத்தை தேர்ந்தெடுக்கவும்',
    'profile.supplier': 'சப்ளையர்',
    'profile.advisor': 'ஆலோசகர்',
    'profile.supplierDesc': 'விவசாய பொருட்கள் மற்றும் சேவைகளை வழங்கவும்',
    'profile.advisorDesc': 'விவசாய நிபுணத்துவம் மற்றும் வழிகாட்டுதலை பகிரவும்',
    'profile.businessInfo': 'வணிக தகவல்',
    'profile.businessName': 'வணிக பெயர்',
    'profile.contactPerson': 'தொடர்பு நபர்',
    'profile.email': 'மின்னஞ்சல் முகவரி',
    'profile.phone': 'தொலைபேசி எண்',
    'profile.address': 'முகவரி',
    'profile.district': 'மாவட்டம்',
    'profile.province': 'மாகாணம்',
    'profile.description': 'விளக்கம்',
    'profile.website': 'வலைதளம்',
    'profile.established': 'நிறுவப்பட்ட ஆண்டு',
    'profile.specialization': 'நிபுணத்துவம்',
    'profile.certification': 'சான்றிதழ்கள்',
    'profile.experience': 'அனுபவம்',
    'profile.save': 'சேமிக்கவும்',
    'profile.cancel': 'ரத்து செய்யவும்',
    'profile.edit': 'திருத்தவும்',
    'profile.myProducts': 'என் தயாரிப்புகள்',
    'profile.myServices': 'என் சேவைகள்',
    'profile.addProduct': 'தயாரிப்பு சேர்க்கவும்',
    'profile.addService': 'சேவை சேர்க்கவும்',

    // Enhanced Product Fields
    'profile.productListings': 'தயாரிப்பு பட்டியல்',
    'profile.nutritionalLevel': 'ஊட்டச்சத்து நிலை',
    'profile.ingredients': 'பொருட்கள்',
    'profile.addIngredient': 'பொருள் சேர்க்கவும்',
    'profile.ingredientName': 'பொருளின் பெயர்',
    'profile.percentage': 'சதவீதம்',
    'profile.npkRatio': 'NPK விகிதம்',
    'profile.nitrogen': 'நைட்ரஜன் (N)',
    'profile.phosphorus': 'பாஸ்பரஸ் (P)',
    'profile.potassium': 'பொட்டாசியம் (K)',

    // Delivery Page
    'delivery.title': 'விநியோகத்தை கண்காணிக்கவும்',
    'delivery.subtitle': 'உங்கள் ஆர்டர்கள் மற்றும் விநியோகங்களை கண்காணிக்கவும்',
    'delivery.backToDashboard': 'டாஷ்போர்டுக்கு திரும்பு',
    'delivery.activeDeliveries': 'செயலில் உள்ள விநியோகங்கள்',
    'delivery.manualTrack': 'கைமுறை கண்காணிப்பு',
    'delivery.trackingNumber': 'கண்காணிப்பு எண்',
    'delivery.enterTracking': 'கண்காணிப்பு எண்ணை உள்ளிடவும்',
    'delivery.trackButton': 'கண்காணிக்கவும்',
    'delivery.recentDeliveries': 'சமீபத்திய விநியோகங்கள்',
    'delivery.allDeliveries': 'அனைத்து விநியோகங்கள்',
    'delivery.orderNumber': 'ஆர்டர் எண்',
    'delivery.status': 'நிலை',
    'delivery.estimatedDelivery': 'மதிப்பிடப்பட்ட விநியோகம்',
    'delivery.location': 'இடம்',
    'delivery.viewDetails': 'விவரங்களை பார்க்கவும்',
    'delivery.contactDriver': 'ஓட்டுநரை தொடர்பு கொள்ளவும்',
    
    // Add more Tamil translations...
    'filters.title': 'வடிகட்டிகள்',
    'products.found': 'தயாரிப்புகள் கண்டறியப்பட்டன',
    'footer.description': 'தர விவசாய வளங்கள் மற்றும் நிபுணர் ஆலோசனையுடன் விவசாயிகளை இணைக்கிறது.',
    'lang.sinhala': 'සිංහල',
    'lang.english': 'English',
    'lang.tamil': 'தமிழ்',
    'lang.selectLanguage': 'மொழியை தேர்ந்தெடுக்கவும்',
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('si'); // Default to Sinhala

  const t = (key: string): string => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}